### ISSUE TITLE
Remove json workaround

### ISSUE THREAD

**Issue by Subbitoooo** [software-mansion/starknet.swift#115]
All right,to remove the JSON workaround in StarkNet, you can use native StarkNet data types and functions instead of converting data to JSON and back. This can make your code more efficient and easier to read. Hoping that This can help you to solve your problem. If you have any question, just ask me ;)

**Comment by DelevoXDG** [comment]
Hey,
as I stated [in my reply](https://github.com/software-mansion/starknet.swift/issues/113#issuecomment-1789466997) in #113, there are no plans to do significant changes to serialization. 

The objective of the SDK is to be user-friendly to swift users and current solutions successfully accomplishes that.

If you have more questions or clarifications, let me know!

**Comment by Subbitoooo** [comment]
No question,  Your answer was exhaustive. Thanks ;)
