### ISSUE TITLE
Use old approach to create accounts using sncast  

### ISSUE THREAD

**Issue by DelevoXDG** [software-mansion/starknet.swift#130]
### Feature Request

Because newer cast versions with 0.6.0 support don't properly work with tmp directories as of now, currently we have to use a workaround: instead of running `sncast account create`, we use prepared accounts file with accounts.

This should be changed to use old approach once update to sncast is possible.

Blocked by: https://github.com/foundry-rs/starknet-foundry/pull/1093

**Comment by THenry14** [comment]
to be determined
