### ISSUE TITLE
Deploy account in the first Invoke/Declare transaction

### ISSUE THREAD

**Issue by mrMateosantana** [software-mansion/starknet.swift#146]
### Feature Request

With Starknet v3 transactions one can now deploy the account with the first declare/invoke. Would be cool to have this feature.
As I can see the structure is there, and `StarknetInvokeTransactionV3` has the appropriate field for this `accountDeploymentData`. Is it possible to use this feature at the current state of the library?

`Deploy account in the first Invoke/Declare transaction: In line with the concept presented in EIP-4337, we propose adding an account_deployment_data field to Invoke and Declare transactions sent from a non-existing contract, eliminating the need for a separate transaction to deploy an account.

account_deployment_data is used to deploy an account contract that contains the entrypoints: __validate__, __execute___, and in the case of Declare, also __validate_declare__.`

Source: [Transactions V3](https://github.com/starknet-io/SNIPs/blob/main/SNIPS/snip-8.md)

**Comment by mrMateosantana** [comment]
Okey, should confirm but seems that the fact we are already with V3 transactions doesn't imply that the account_deploy_data is available.

**Comment by DelevoXDG** [comment]
Hi @mrMateosantana 

>  Is it possible to use this feature at the current state of the library?

Unfortunately, it's not. Most transaction v3 features are not available as of Starknet 0.13.0, as per [SNIP-10](https://github.com/ob1337/SNIPs/blob/snip-10/SNIPS/snip-10.md). The SDK does not allow setting any of these fields to avoid you sending an invalid transaction.

You can checkout [tests](https://github.com/software-mansion/starknet.swift/blob/ad1cd44fe728d70c3a846188294eecc447d38e63/Tests/StarknetTests/Accounts/AccountTest.swift#L171) as a reference for deploying an account using a dedicated transaction.

**Comment by mrMateosantana** [comment]
Thank you very much for your patience @DelevoXD. I'm just getting started with Starknet overall so I don't have a clear view of whats available and what not.

**Comment by DelevoXDG** [comment]
@mrMateosantana 
Sure, feel free to reach out if you have any questions!
