### ISSUE TITLE
How to format tuples

### ISSUE THREAD

**Issue by mrMateosantana** [software-mansion/starknet.swift#149]
### Feature Request

Hey,
I was wondering how I can format the call data for a constructor/function such as this:
```rust
 fn constructor(
        ref self: ContractState, signers: Array<(ContractAddress, felt252)>, threshold: usize
    ) { ...
```
The Python starknet library for example handles this 
<img width="749" alt="image" src="https://github.com/software-mansion/starknet.swift/assets/157704598/e50a6c65-9eb8-42c4-83f6-0f065a86e571">

@DelevoXDG  But have no idea how to handle this in Swift, maybe you can throw some light to me?
<img width="722" alt="image" src="https://github.com/software-mansion/starknet.swift/assets/157704598/8ef598a6-dda6-4d9c-b80e-63086656c553">

**Comment by mrMateosantana** [comment]
Yes deploy a MOA account, but it should be done through UDC because that's how it is intended to. 
So you mean I need to flatten the array? 
Something like from:
```swift
let calldata = [[(arg1, arg2), (arg3, arg4)], arg5]
```
To something like?
```swift
let calldata = [arg1, arg2, arg3, arg4, arg5]
```
I have some trouble understanding how does really really starknet rpc parses the args in that case.

**Comment by DelevoXDG** [comment]
> Yes deploy a MOA account, but it should be done through UDC because that's how it is intended to.

Normally, accounts should be deployed using `DEPLOY_ACCOUNT` transaction. Please note that starknet.swift does not have a built-in support for declaring or deploying contracts. You can of course take inspiration from other tools e.g. [starknet.jvm](https://github.com/software-mansion/starknet-jvm/blob/main/lib/src/main/kotlin/com/swmansion/starknet/deployercontract/StandardDeployer.kt) and apply the same logic when invoking `deployContract`, but it's unlikely currently the best tool for the job.

> So you mean I need to flatten the array?

You're correct. Unlike tuples, normally you also have to prepend array length as `Felt` before the array elements, so it will be
```swift
let calldata = [2, arg1, arg2, arg3, arg4, arg5]
```

> I have some trouble understanding how does really really starknet rpc parses the args in that case. So from what I can see the end statement to my case is, that starknet.swift doesn't yet support tuple serialization to cairo right?
 
We don't interact with Cairo per se, all `calldata` values should be serialized (flattened) to their `Felt` representations, including tuples, structs, etc. so later they can be deserialized upon transaction execution. In case of starknet.swift, you will have to convert most of the types manually.

**Comment by mrMateosantana** [comment]
Thank you, yes I was able to get it to work. As you said, it was about prepending the array length fact that was the missing piece for me.
